services:
  postgres:
    image: postgres:16.3-alpine
    container_name: db-recipes
    env_file:
      - .env.local
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
